-- ================================================================
-- UtilitySense: Department Hierarchy, Access Control & Module Configuration Migration
-- Execute in Supabase SQL Editor
-- ================================================================

-- 1) Enhance 'departments' table with Location, Plant and Module configuration
ALTER TABLE public.departments ADD COLUMN IF NOT EXISTS plant_code TEXT;
ALTER TABLE public.departments ADD COLUMN IF NOT EXISTS location TEXT;
ALTER TABLE public.departments ADD COLUMN IF NOT EXISTS enabled_modules JSONB DEFAULT '{"electricity":true,"solar":true,"diesel":true,"gas":true,"water":true,"waste":true,"production":true,"moulding":true}'::jsonb;
ALTER TABLE public.departments ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now());

-- Create index on location and plant_code for fast department lookups
CREATE INDEX IF NOT EXISTS idx_departments_plant ON public.departments(plant_code);
CREATE INDEX IF NOT EXISTS idx_departments_location ON public.departments(location);

-- 2) Enhance 'users' table with allowed_departments
-- Values: 'all', 'none', or comma-separated department codes (e.g. 'RD,PROD')
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS allowed_departments TEXT DEFAULT 'none';

-- 3) Relational user_department_access table (Normalized mapping structure)
CREATE TABLE IF NOT EXISTS public.user_department_access (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    plant_code TEXT NOT NULL,
    dept_code TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_user_dept_user_id ON public.user_department_access(user_id);
CREATE INDEX IF NOT EXISTS idx_user_dept_plant_dept ON public.user_department_access(plant_code, dept_code);

-- 4) Index on daily_entries for fast plant + department + date queries
CREATE INDEX IF NOT EXISTS idx_daily_entries_plant_dept_date ON public.daily_entries(plant, department, date DESC);

-- 5) Default department seeding for existing plants (Safe & Non-Destructive)
INSERT INTO public.departments (dept_code, dept_name, location, plant_code, status, enabled_modules)
VALUES
    ('PROD', 'Production', 'PUNE', '4010', 'Active', '{"electricity":true,"solar":true,"diesel":true,"gas":true,"water":true,"waste":true,"production":true,"moulding":false}'::jsonb),
    ('MOULD', 'Moulding', 'PUNE', '4010', 'Active', '{"electricity":true,"solar":false,"diesel":false,"gas":false,"water":false,"waste":false,"production":true,"moulding":true}'::jsonb),
    ('RD', 'R&D', 'PUNE', '4010', 'Active', '{"electricity":true,"solar":true,"diesel":true,"gas":true,"water":true,"waste":true,"production":false,"moulding":false}'::jsonb),
    ('MAINT', 'Maintenance', 'PUNE', '4010', 'Active', '{"electricity":true,"solar":true,"diesel":true,"gas":true,"water":true,"waste":true,"production":false,"moulding":false}'::jsonb)
ON CONFLICT (dept_code) DO NOTHING;
