-- ================================================================
-- UtilitySense Feature Enhancements: Audit Logs & Email Automation
-- Execute in Supabase SQL Editor
-- ================================================================

-- 1) Audit Logs Table (Tamper-Resistant Security & Operation Tracking)
CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email TEXT NOT NULL,
    user_id TEXT,
    user_name TEXT,
    action TEXT NOT NULL,          -- 'CREATE', 'UPDATE', 'DELETE', 'EXPORT', 'LOGIN', 'LOGOUT', 'SETTINGS_CHANGE'
    module TEXT NOT NULL,          -- 'Daily Operations', 'Tariff Rates', 'Multiply Factors', 'Plants', 'Users', 'Reports', 'Auth', 'Settings'
    record_id TEXT,
    location TEXT,
    plant TEXT,
    old_value JSONB,
    new_value JSONB,
    status TEXT DEFAULT 'SUCCESS', -- 'SUCCESS', 'FAILED', 'WARNING'
    ip_device TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Index for fast audit queries
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON audit_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_module ON audit_logs(module);
CREATE INDEX IF NOT EXISTS idx_audit_logs_user ON audit_logs(user_email);

-- 2) Email Automation Configurations Table (IT Admin Only)
CREATE TABLE IF NOT EXISTS email_automation_configs (
    id TEXT PRIMARY KEY DEFAULT 'default_monthly_report',
    enabled BOOLEAN DEFAULT FALSE,
    schedule_time TEXT DEFAULT '10:00',
    location TEXT DEFAULT 'all',
    plants TEXT DEFAULT 'all',
    recipients TEXT,
    subject_template TEXT DEFAULT 'Monthly UtilitySense Report - {Plant} ({Month})',
    body_template TEXT DEFAULT 'Dear Sir,\n\nPlease find attached the monthly UtilitySense report for {Location} - {Plant} for {Month}.\n\nRegards,\nUtilitySense Management',
    last_sent_at TIMESTAMPTZ,
    last_status TEXT,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

-- 3) Unique constraint to prevent duplicate dates per plant on daily_entries
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'uq_daily_entries_plant_date'
    ) THEN
        ALTER TABLE daily_entries ADD CONSTRAINT uq_daily_entries_plant_date UNIQUE (plant, date);
    END IF;
EXCEPTION
    WHEN others THEN
        RAISE NOTICE 'Constraint already exists or duplicates exist in historic records: %', SQLERRM;
END $$;
