-- ================================================================
-- UtilitySense Feature Enhancements: Audit Logs & Multi-Schedule Email Reports
-- Execute in Supabase SQL Editor
-- ================================================================

-- 1) Audit Logs Table (Tamper-Resistant Security & Operation Tracking)
CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email TEXT NOT NULL,
    user_id TEXT,
    user_name TEXT,
    action TEXT NOT NULL,          -- 'CREATE', 'UPDATE', 'DELETE', 'EXPORT', 'LOGIN', 'LOGOUT', 'SETTINGS_CHANGE'
    module TEXT NOT NULL,          -- 'Daily Operations', 'Tariff Rates', 'Multiply Factors', 'Plants', 'Users', 'Reports', 'Auth', 'Settings', 'Email Automation'
    record_id TEXT,
    location TEXT,
    plant TEXT,
    old_value JSONB,
    new_value JSONB,
    status TEXT DEFAULT 'SUCCESS', -- 'SUCCESS', 'FAILED', 'WARNING'
    ip_device TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Index for fast audit queries
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON audit_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_module ON audit_logs(module);
CREATE INDEX IF NOT EXISTS idx_audit_logs_user ON audit_logs(user_email);

-- 2) Multi-Schedule Email Reports Table (IT Admin Only)
CREATE TABLE IF NOT EXISTS email_schedules (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    location TEXT NOT NULL,
    plant TEXT NOT NULL,
    report_type TEXT DEFAULT 'Monthly Utility Report',
    frequency TEXT DEFAULT 'Monthly',
    schedule_day INTEGER DEFAULT 1,
    schedule_time TEXT DEFAULT '10:00',
    to_recipients TEXT NOT NULL,
    cc_recipients TEXT,
    bcc_recipients TEXT,
    subject_template TEXT DEFAULT 'Monthly Utility Report - {Location} - {Plant} - {Month}',
    body_template TEXT DEFAULT 'Dear Team,\n\nPlease find attached the monthly UtilitySense report for {Location} - {Plant} for {Month}.\n\nPlease review the report and take necessary action where required.\n\nRegards,\nUtilitySense Management',
    enabled BOOLEAN DEFAULT TRUE,
    last_run_at TIMESTAMPTZ,
    last_status TEXT,
    created_by TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Index for schedule queries
CREATE INDEX IF NOT EXISTS idx_email_schedules_location ON email_schedules(location);
CREATE INDEX IF NOT EXISTS idx_email_schedules_plant ON email_schedules(plant);

-- 3) Email Schedule Execution Logs Table
CREATE TABLE IF NOT EXISTS email_schedule_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_id TEXT NOT NULL,
    schedule_name TEXT,
    location TEXT,
    plant TEXT,
    to_recipients TEXT,
    cc_recipients TEXT,
    status TEXT NOT NULL, -- 'SUCCESS', 'FAILED'
    error_message TEXT,
    executed_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_email_schedule_logs_sched_id ON email_schedule_logs(schedule_id);
CREATE INDEX IF NOT EXISTS idx_email_schedule_logs_exec_at ON email_schedule_logs(executed_at DESC);

-- 4) Unique constraint to prevent duplicate dates per plant on daily_entries
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'uq_daily_entries_plant_date'
    ) THEN
        ALTER TABLE daily_entries ADD CONSTRAINT uq_daily_entries_plant_date UNIQUE (plant, date);
    END IF;
EXCEPTION
    WHEN others THEN
        RAISE NOTICE 'Constraint already exists or duplicates exist in historic records: %', SQLERRM;
END $$;
